[Documents for @litert/jwt](../../index.md) / [Errors](../index.md) / E\_VERIFY\_FAILED

# Class: E\_VERIFY\_FAILED

Defined in: [src/lib/Errors.ts:75](https://github.com/litert/jwt.js/blob/master/src/lib/Errors.ts#L75)

The error indicating that the verification process failed, including
parsing, signature verification and claims validation.

## Extends

- [`JwtError`](JwtError.md)

## Constructors

### Constructor

> **new E\_VERIFY\_FAILED**(`code`, `context`, `origin`): `E_VERIFY_FAILED`

Defined in: [src/lib/Errors.ts:53](https://github.com/litert/jwt.js/blob/master/src/lib/Errors.ts#L53)

#### Parameters

##### code

[`EErrorCode`](../enumerations/EErrorCode.md)

##### context

`IDict` = `{}`

##### origin

`unknown` = `null`

#### Returns

`E_VERIFY_FAILED`

#### Inherited from

[`JwtError`](JwtError.md).[`constructor`](JwtError.md#constructor)

## Properties

### cause?

> `optional` **cause**: `unknown`

Defined in: node\_modules/typescript/lib/lib.es2022.error.d.ts:26

#### Inherited from

[`JwtError`](JwtError.md).[`cause`](JwtError.md#cause)

***

### code

> `readonly` **code**: [`EErrorCode`](../enumerations/EErrorCode.md)

Defined in: [src/lib/Errors.ts:41](https://github.com/litert/jwt.js/blob/master/src/lib/Errors.ts#L41)

The reason code of the exception.

#### Inherited from

[`JwtError`](JwtError.md).[`code`](JwtError.md#code)

***

### context

> `readonly` **context**: `IDict`

Defined in: [src/lib/Errors.ts:31](https://github.com/litert/jwt.js/blob/master/src/lib/Errors.ts#L31)

Context of the exception.

> Note:
> It's not recommended to use bigint and code types as values/keys in the context,
> which is not supported by JSON serialization.

#### Inherited from

[`JwtError`](JwtError.md).[`context`](JwtError.md#context)

***

### message

> **message**: `string`

Defined in: node\_modules/typescript/lib/lib.es5.d.ts:1077

#### Inherited from

[`JwtError`](JwtError.md).[`message`](JwtError.md#message)

***

### name

> **name**: `string`

Defined in: node\_modules/typescript/lib/lib.es5.d.ts:1076

#### Inherited from

[`JwtError`](JwtError.md).[`name`](JwtError.md#name)

***

### origin

> `readonly` **origin**: `unknown`

Defined in: [src/lib/Errors.ts:36](https://github.com/litert/jwt.js/blob/master/src/lib/Errors.ts#L36)

The origin of the exception.

#### Inherited from

[`JwtError`](JwtError.md).[`origin`](JwtError.md#origin)

***

### stack?

> `optional` **stack**: `string`

Defined in: node\_modules/typescript/lib/lib.es5.d.ts:1078

#### Inherited from

[`JwtError`](JwtError.md).[`stack`](JwtError.md#stack)

***

### errorMessage

> `readonly` `static` **errorMessage**: `"The verification process failed."` = `'The verification process failed.'`

Defined in: [src/lib/Errors.ts:79](https://github.com/litert/jwt.js/blob/master/src/lib/Errors.ts#L79)

The description of the error.

#### Overrides

[`JwtError`](JwtError.md).[`errorMessage`](JwtError.md#errormessage)

***

### errorName

> `readonly` `static` **errorName**: `"verify_failed"` = `'verify_failed'`

Defined in: [src/lib/Errors.ts:77](https://github.com/litert/jwt.js/blob/master/src/lib/Errors.ts#L77)

The error name.

#### Overrides

[`JwtError`](JwtError.md).[`errorName`](JwtError.md#errorname)

***

### stackTraceLimit

> `static` **stackTraceLimit**: `number`

Defined in: node\_modules/@types/node/globals.d.ts:68

The `Error.stackTraceLimit` property specifies the number of stack frames
collected by a stack trace (whether generated by `new Error().stack` or
`Error.captureStackTrace(obj)`).

The default value is `10` but may be set to any valid JavaScript number. Changes
will affect any stack trace captured _after_ the value has been changed.

If set to a non-number value, or set to a negative number, stack traces will
not capture any frames.

#### Inherited from

[`JwtError`](JwtError.md).[`stackTraceLimit`](JwtError.md#stacktracelimit)

## Methods

### captureStackTrace()

> `static` **captureStackTrace**(`targetObject`, `constructorOpt?`): `void`

Defined in: node\_modules/@types/node/globals.d.ts:52

Creates a `.stack` property on `targetObject`, which when accessed returns
a string representing the location in the code at which
`Error.captureStackTrace()` was called.

```js
const myObject = {};
Error.captureStackTrace(myObject);
myObject.stack;  // Similar to `new Error().stack`
```

The first line of the trace will be prefixed with
`${myObject.name}: ${myObject.message}`.

The optional `constructorOpt` argument accepts a function. If given, all frames
above `constructorOpt`, including `constructorOpt`, will be omitted from the
generated stack trace.

The `constructorOpt` argument is useful for hiding implementation
details of error generation from the user. For instance:

```js
function a() {
  b();
}

function b() {
  c();
}

function c() {
  // Create an error without stack trace to avoid calculating the stack trace twice.
  const { stackTraceLimit } = Error;
  Error.stackTraceLimit = 0;
  const error = new Error();
  Error.stackTraceLimit = stackTraceLimit;

  // Capture the stack trace above function b
  Error.captureStackTrace(error, b); // Neither function c, nor b is included in the stack trace
  throw error;
}

a();
```

#### Parameters

##### targetObject

`object`

##### constructorOpt?

`Function`

#### Returns

`void`

#### Inherited from

[`JwtError`](JwtError.md).[`captureStackTrace`](JwtError.md#capturestacktrace)

***

### prepareStackTrace()

> `static` **prepareStackTrace**(`err`, `stackTraces`): `any`

Defined in: node\_modules/@types/node/globals.d.ts:56

#### Parameters

##### err

`Error`

##### stackTraces

`CallSite`[]

#### Returns

`any`

#### See

https://v8.dev/docs/stack-trace-api#customizing-stack-traces

#### Inherited from

[`JwtError`](JwtError.md).[`prepareStackTrace`](JwtError.md#preparestacktrace)
